Make TaskController class
CodeSoom/spring-week2-assignment-1 pull request #14
Opened 2021-01-25 16:10 UTC by mikekang47

Make list, create method

- [ ] Read collection

- [ ] Read Item

- [ ] Create

- [ ] Update

- [ ] Delete

2021-01-26 13:25 UTC, hannut91 requested changes

2021-01-26 13:25 UTC, hannut91 commented on app/src/main/java/com/codesoom/assignment/controllers/TaskController.java
> +    private Long newId = 0L;
`new`가 붙은 이유는 무엇인가요?

2021-01-26 13:25 UTC, hannut91 commented on app/src/main/java/com/codesoom/assignment/controllers/TaskController.java
> +    {
여기만 중괄호가 아래로 내려온 것 같아요

2021-01-26 13:25 UTC, hannut91 commented on app/src/main/java/com/codesoom/assignment/models/App.java
> +package com.codesoom.assignment.models;
패키지가 여기로 이동한 이유가 무엇인가요?

2021-01-26 13:25 UTC, hannut91 commented on app/src/main/java/com/codesoom/assignment/controllers/TaskController.java
> +
여기 두 줄이 띄어져 있는데 혹시 의도가 있을까요?

2021-01-26 13:25 UTC, hannut91 commented on app/src/main/java/com/codesoom/assignment/controllers/TaskController.java
> +
여기도 두 줄이 띄어져 있는데 의도가 있을까요?

2021-01-26 14:15 UTC, mikekang47 commented on app/src/main/java/com/codesoom/assignment/controllers/TaskController.java
> +    {
수정하겠습니다!

2021-01-26 14:35 UTC, mikekang47 commented on app/src/main/java/com/codesoom/assignment/models/App.java
> +package com.codesoom.assignment.models;
models폴더를 만들면서 잘못 옮겨진거 같네요..수정하겠습니다

2021-01-27 16:50 UTC, hannut91 commented on app/src/main/java/com/codesoom/assignment/controllers/TaskController.java
> +    private Long Id = 0L;
`TaskController`가 `tasks`를 어떻게 관리할지, 그리고 비즈니스 로직을 모두 가지고 있는 것 같아요. 관심사에 따라 적절히 분리할 수 있을까요?

2021-01-27 16:50 UTC, hannut91 commented on app/src/main/java/com/codesoom/assignment/controllers/TaskController.java
> +    @PutMapping("/{id}")
위에 빈 줄을 추가해서 구분해주면 좋을 것 같아요

2021-01-27 16:50 UTC, hannut91 commented on app/src/main/java/com/codesoom/assignment/controllers/TaskController.java
> +    {
여기도 중괄호가 아래로 내려온 것 같아요

2021-01-27 16:50 UTC, hannut91 commented on app/src/main/java/com/codesoom/assignment/controllers/TaskController.java
> +    }
수정할 task이고 변수의 Variable의 Var를 합쳐서 `updateVar`라고 이름지으신 것 같아요. 아주 자명한 경우가 아니라면 줄임말은 사용하시면 안되고, `update`라는 단어가 무언가를 수정할 것 같아서 이름이 적절하지 않은 것 같아요.

`body`에서 받아오는 것을 `source`같은 것으로 하고 여기는 `task`라고 하는 것은 어떨까요?

2021-01-27 16:50 UTC, hannut91 commented on app/src/main/java/com/codesoom/assignment/controllers/TaskController.java
> +    }
tasks에서 우리가 원하는 task를 찾지 못할 경우 null을 반환하고 있는 것 같아요.
이 함수를 사용하는 입장에서는 이 함수가 null을 반환할 수 있는지 예상할 수 없고, 그리고 null처리를 하지 않아도
자바 컴파일러는 아무런 불만도 표현하지 않기 때문에 위험성이 있는 것 같아요. 만약 반환 타입을 Optional 그대로 반환한다면, 함수의 Signature에서 이 값이 있을 수도 있고 없을 수도 있다는 의도를 드러내고 있고, 없는 경우를 처리하지 않으면 컴파일도 되지 않아서 에러 처리를 강제할 수 있어요

하지만 Optional 반환은 다른 부분이 어떻게 만들어졌냐가 관건이라고 보는데, 함수형으로 처리 중이 아니라면 예외가 가장 일반적이죠. Optional을 리턴하면 사용하는 쪽에서 비슷한 코드를 작성해야 하기 때문에 사용하기 힘든 인터페이스가 될 가능성이 커요.

2021-01-27 16:50 UTC, hannut91 commented on app/src/main/java/com/codesoom/assignment/controllers/TaskController.java
> +    }
`Id`의 `I`는 소문자로 시작하는게 좋을 것 같아요

2021-01-27 16:50 UTC, hannut91 commented on app/src/main/java/com/codesoom/assignment/controllers/TaskController.java
> +    }
여기도 중괄호가 내려왔고 테스트를 보시면 `No Content`로 응답해야 합니다.

2021-01-28 04:28 UTC, mikekang47 commented on app/src/main/java/com/codesoom/assignment/controllers/TaskController.java
> +    }
감사합니다~

2021-01-28 13:36 UTC, hannut91 commented
관심사의 분리도 꼭 해보세요!

2021-01-28 13:38 UTC, mikekang47 commented
네! 도전해보겠습니다!

2021년 1월 28일 (목) 오후 10:36, Yunseok <notifications@github.com>님이 작성:

> 관심사의 분리도 꼭 해보세요!
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/CodeSoom/spring-week2-assignment-1/pull/14#issuecomment-769056975>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQ2YRFTL2H2NAMP5GR5IS5DS4FR7NANCNFSM4WR7MOLA>
> .
>

2021-01-29 14:27 UTC, hannut91 commented on app/src/main/java/com/codesoom/assignment/controllers/TaskController.java
> +    private TaskRepository taskRepository = new TaskRepository();
`Repository`란 데이터 접근에 대한 것을 추상화 한 것입니다.
`Controller`는 Client에서 요청온 것을 받고 다시 돌려주는 역할을 하고 있습니다.
`클라이언트 요청 => ? => 데이터 접근 => ? => 클라이언트에게 응답`
같은 모양이 되었습니다. 중간에 실제로 우리의 애플리케이션이 하는 일이 빠져있습니다.

2021-01-29 14:27 UTC, hannut91 commented on app/src/main/java/com/codesoom/assignment/controllers/TaskController.java
> +    }
사용자의 요청을 처리하고 응답을 돌려주는 컨트롤러에서 우리가 아이디를 만드는 방법을 알고 있습니다!

2021-01-30 01:57 UTC, mikekang47 commented on app/src/main/java/com/codesoom/assignment/controllers/TaskController.java
> +    }
generateId를 사용할 필요가 없다는 말씀이신가요...?

2021-01-30 13:36 UTC, hannut91 commented on app/src/main/java/com/codesoom/assignment/controllers/TaskController.java
> +
빈 줄은 한 줄만 띄어서 구분해도 좋을 것 같아요 ㅎㅎ

2021-01-30 13:36 UTC, hannut91 commented on app/src/main/java/com/codesoom/assignment/repositories/TaskRepository.java
> +            throw new TaskNotFoundException();
`if`문을 사용할 때 한 줄이라도 괄호를 사용하는게 좋습니다

2021-01-30 13:36 UTC, hannut91 commented on app/src/main/java/com/codesoom/assignment/repositories/TaskRepository.java
> +    public List<Task> getTasks() {
위에 빈 줄을 하나 추가해서, 변수를 선언한 곳과 메서드를 사용한 곳을 구분해주면 좋을 것 같아요

2021-01-30 13:36 UTC, hannut91 commented on app/src/main/java/com/codesoom/assignment/controllers/TaskController.java
> +    }
`Controller`에서 `id`가 어떻게 만들어지고 있는지 알고 있습니다. 요청과 응답에 대한 처리 뿐만 아니라 아이디를 어떻게 관리할 건지도 컨트롤러에서 관리하고 있습니다

2021-01-31 14:09 UTC, hannut91 approved these changes
고생하셨습니다! ㅎㅎ 이번 과제를 통해서 무엇을 배우셨나요?

2021-01-31 14:11 UTC, mikekang47 commented
> 고생하셨습니다! ㅎㅎ 이번 과제를 통해서 무엇을 배우셨나요?

감사합니다!!! 이번에도 과제 통과 못하면 어쩌나   고생했네요ㅋㅋㅋ 주간회고에서도 언급하겠지만 스프링이 너무나 강력하네요!!

2021-02-07 13:16 UTC, merged