Spring Web으로 ToDo REST API 만들기
CodeSoom/spring-week2-assignment-1 pull request #4
Opened 2021-01-25 05:33 UTC by dperformance

스프링 컨트롤러 방식으로 변경

1. Read Collection - GET /tasks      => 완료
2. Read Item - GET /tasks/{id}       => 완료
3. Create - POST /tasks              => 완료
4. Update - PUT/PATCH /tasks/{id}    => 완료
5. Delete - DELETE /tasks/{id}       => 완료

2021-01-25 14:45 UTC, hannut91 requested changes
고생하셨어요 ㅎㅎ

2021-01-25 14:45 UTC, hannut91 commented on app/src/main/java/com/codesoom/assignment/models/Task.java
> +    }
String.format을 사용해서 표현하는 건 어떨까요? 다음과 같이 표현할 수 있을거에요

```java
return String.format("{ id = %s, title = %s }", id, title);
```

더 좋은건 Template literal이지만 자바에서는 지원하질 않네요 ㅠ 만약 이런게 지원하는 코틀린을 사용했다면 다음과 같이 사용할 수 있을거에요

```kotlin
return "{ id = $id, title = $title }"
```

2021-01-25 14:45 UTC, hannut91 commented on app/src/main/java/com/codesoom/assignment/controllers/TaskController.java
> +    }
`tasks`에서 우리가 원하는 task를 찾지 못할 경우 `null`을 반환하고 있는 것 같아요.
이 함수를 사용하는 입장에서는 이 함수가 `null`을 반환할 수 있는지 예상할 수 없고, 그리고 `null`처리를 하지 않아도
자바 컴파일러는 아무런 불만도 표현하지 않기 때문에 위험성이 있는 것 같아요. 만약 반환 타입을 Optional 그대로 반환한다면, 함수의 Signature에서 이 값이 있을 수도 있고 없을 수도 있다는 의도를 드러내고 있고, 없는 경우를 처리하지 않으면 컴파일도 되지 않아서 에러 처리를 강제할 수 있어요

2021-01-25 14:45 UTC, hannut91 commented on app/src/main/java/com/codesoom/assignment/controllers/TaskController.java
> +    }
주어진 조건을 맞으면 `false`를 반환, 그렇지 않다면 `true`를 반환하고 있어요. 이럴 경우에는 조건식을 바로 반환해도 될 것 같아요

```java
private boolean findTaskId(int id) {
    return id == 0 || tasks.size() <= id -1;
}
```

2021-01-25 14:45 UTC, hannut91 commented on app/src/main/java/com/codesoom/assignment/controllers/TaskController.java
> +        tasks.remove(id -1);
계속 `-1`을 해주는데 우연히 index와 id가 같은 경우에만 올바르게 동작해요. 만약에 task 목록 중간의 task를 삭제할 경우 문제가 생길 수 있을 것 같아요

2021-01-26 10:51 UTC, dperformance commented on app/src/main/java/com/codesoom/assignment/models/Task.java
> +    }
조언감사합니다 ㅎㅎ 말씀해주신대로 수정했습니다.

2021-01-26 10:54 UTC, dperformance commented on app/src/main/java/com/codesoom/assignment/controllers/TaskController.java
> +    }
이 부분은 공부를 해서 수정해보도록 할께요!! 
스트림을 잘 이해하지 못하고 사용한거라서 말씀해주신 사항 잘 고려해서 수정해보겠습니다 ㅎ

2021-01-26 14:06 UTC, hannut91 commented on app/src/main/java/com/codesoom/assignment/controllers/TaskController.java
> +    }
지웠다는 메세지를 클라이언트에 응답해주고 계시군요 ㅎㅎ 테스트에서는 지금 NO_CONTENT를 기대하고 있습니다. 테스트를 수정하던지 아니면 여기를 수정해야 할거에요 ㅎㅎ

2021-01-26 14:06 UTC, hannut91 commented on app/src/main/java/com/codesoom/assignment/controllers/TaskController.java
> +    }
문자열로 변환해서 반화하고 있는 것 같아요. `task`를 그대로 반환하는 것은 어떨까요?

2021-01-26 14:06 UTC, hannut91 commented on app/src/main/java/com/codesoom/assignment/controllers/TaskController.java
> +    }
++를 붙여서 계산된 값을 반환하고 있는 것 같아요. `++`는 너무 함축된 의미라서 좋지 않습니다. 코드가 더 길더라도 명시적인게 좋은 것 같아요

2021-01-27 16:02 UTC, hannut91 commented
잘 진행되고 계신가요? ㅎㅎ 도움이 필요하시면 말씀해주세요!

2021-01-27 16:14 UTC, hannut91 commented on app/src/main/java/com/codesoom/assignment/controllers/TaskController.java
> +    private final static String NO_SEARCH_ID = "입력하신 ID는 존재하지 않습니다.zz";
`TaskController`가 우리의 비즈니스 로직과 데이터를 어떻게 다뤄야 하는지 모두 알고 있는 것 같아요. 컨트롤러의 역할이 무엇인지 잘 생각해보시고 관심사의 분리를 해보는건 어떨까요?

2021-01-28 09:24 UTC, dperformance commented on app/src/main/java/com/codesoom/assignment/controllers/TaskController.java
> +    private final static String NO_SEARCH_ID = "입력하신 ID는 존재하지 않습니다.zz";
Controller, service, repository로 나누어보았습니다.

2021-01-28 09:55 UTC, dperformance commented
marko.js가 생소하네요 ㅎㅎ.

2021-01-28 09:56 UTC, dperformance commented on app/src/main/java/com/codesoom/assignment/controllers/TaskController.java
> +    }
조언 감사합니다. 수정 하였습니다.

2021-01-28 14:11 UTC, hannut91 commented on app/src/main/java/com/codesoom/assignment/repository/TaskRepository.java
> +    }
`task`를 찾으면 `Task`를 돌려줄 것 같은데 문자열로 돌려주고 있네요

2021-01-28 14:11 UTC, hannut91 commented on app/src/main/java/com/codesoom/assignment/repository/TaskRepository.java
> +        }
`null`을 사용하고있어서 `null`인지 계속 처리를 해야되네요

2021-01-29 14:35 UTC, hannut91 commented on app/src/main/java/com/codesoom/assignment/controllers/TaskController.java
> +    }
`/tasks`가 계속 반복되어 사용되고 있네요. `TaskController`에 `@RequestMapping("/tasks")`를 하면 여기서는 `@GetMapping`만 사용하면 되고 다른 곳에서는 `/tasks`를 생략해서 사용해도 되서 더 단순해질 것 같아요

2021-01-30 13:37 UTC, hannut91 commented
어려움이 있으시다면 과제 풀이를 참고해서 완성해보는 것도 좋을 것 같습니다 ㅎㅎ

2021-01-31 14:12 UTC, hannut91 approved these changes
고생하셨습니다! 채널에 회고를 남겨주셨네요! ㅎㅎ

2021-01-31 14:12 UTC, merged