[week-2] Create a ToDo REST API with Spring
CodeSoom/spring-week2-assignment-1 pull request #8
Opened 2021-01-25 11:59 UTC by min-w-park

2021-01-25 14:55 UTC, hannut91 requested changes
고생하셨어요 ㅎㅎ
풀 리퀘스트 본문으로 같이 작업하는 사람들에게 이 작업이 무슨 작업을 했는지 설명할 수 있습니다.
지금은 과제를 하는 것이지만, 과제를 하면서 무엇을 했는지 간단하게 적어보는 것은 어떨까요?

2021-01-25 14:55 UTC, hannut91 commented on app/src/main/java/com/codesoom/assignment/controllers/TaskController.java
> +    }
여기도 `@ResponseStatus`를 이용해서 상태코드를 정의하는 것은 어떨까요?

2021-01-25 14:55 UTC, hannut91 commented on app/src/main/java/com/codesoom/assignment/controllers/TaskController.java
> +    }
새로운 테스크를 만들기 때문에 `new`라는 말을 붙이신 것 같아요. 제가 생각하기에는 `new`라는 의미가 없어도 충분히 이해될 수 있을 거라고 생각하는데 어떠신가요?

2021-01-25 14:55 UTC, hannut91 commented on app/src/main/java/com/codesoom/assignment/controllers/TaskController.java
> +                .status(HttpStatus.CREATED)
이미 `@ResponseStatus`이 데코레이터로 상태코드를 정의하고 있기 때문에 반환 타입을 `Task`로만 정의하고 `Task`만 반환해도 될 것 같아요

2021-01-25 14:55 UTC, hannut91 commented on app/src/main/java/com/codesoom/assignment/controllers/TaskController.java
> +    }
`ReqeustBody`에서 받는 값을 `source`로 하고, `sourceTask`는 `task`로 써도 좋을 것 같아요

2021-01-25 14:55 UTC, hannut91 commented on app/src/main/java/com/codesoom/assignment/controllers/TaskController.java
> +    }
하나의 메서드가 PATCH와 PUT 둘다 받을 수 있게 할 수 있을까요? 사실 엄밀히 분리하면 PUT과 PATCH는 다르게 사용되기 때문에 이럴 경우는 별로 없지만 한 번 해보시면 좋을 것 같아요 ㅎㅎ

2021-01-25 14:55 UTC, hannut91 commented on app/src/main/java/com/codesoom/assignment/models/Task.java
> +    }
String.format을 사용해서 표현하는 건 어떨까요? 다음과 같이 표현할 수 있을거에요

```java
return String.format("{ id = %s, title = %s }", id, title);
```

더 좋은건 Template literal이지만 자바에서는 지원하질 않네요 ㅠ 만약 이런게 지원하는 코틀린을 사용했다면 다음과 같이 사용할 수 있을거에요

```kotlin
return "{ id = $id, title = $title }"
```

2021-01-25 14:55 UTC, hannut91 commented on app/src/main/java/com/codesoom/assignment/models/Task.java
> +    }
size로 id를 만들면 task 중간을 삭제한 후 새로 만들 경우에 문제가 생길수도 있을 것 같아요

2021-01-26 06:30 UTC, min-w-park commented on app/src/main/java/com/codesoom/assignment/controllers/TaskController.java
> +    }
네, 좋습니다.

2021-01-26 06:34 UTC, min-w-park commented on app/src/main/java/com/codesoom/assignment/controllers/TaskController.java
> +    }
네, 좋습니다. 사실 DTO로 넘어온 객체와 도메인 객체를 보통 분리를 하는게 익숙했는데 
그렇다면, `@RequestBody Task TaskDTO` 와 `Task task = new Task()` 로 했었을 것 같네요.

2021-01-26 06:53 UTC, min-w-park commented on app/src/main/java/com/codesoom/assignment/controllers/TaskController.java
> +                .status(HttpStatus.CREATED)
이 부분이 사실 좀 문제가 있었는데요, ResponseEntity에서 리턴할 때 body와 함께 상태코드를 리턴을 하고 싶으면 저렇게 따로 입력을 해줘야 하더라고요. `ResponseEntity.created(body)` 는 지원을 하지 않네요. 

`@ResponseStatus` 는 그래서 사실 제 역할을 못하는 것 같더라고요. 의미를 주는 목적으로 써놓긴 했네요.

2021-01-26 06:54 UTC, min-w-park commented on app/src/main/java/com/codesoom/assignment/controllers/TaskController.java
> +                .status(HttpStatus.CREATED)
곧 커밋을 할 예정인데요, 거기서는 `TaskResponseEntity.created(task)` 라는 모양으로, `ok(body)` 처럼 비슷한 느낌으로 만들어 봤어요.

2021-01-26 06:56 UTC, min-w-park commented on app/src/main/java/com/codesoom/assignment/controllers/TaskController.java
> +    }
네ㅎㅎ 한 메소드에 매핑을 같이 쓰니깐 되네요.

2021-01-26 06:57 UTC, min-w-park commented on app/src/main/java/com/codesoom/assignment/models/Task.java
> +    }
오, 코틀린 되게 깔끔하네요. 다음 언어는 코틀린으로 할까나..ㅎ

2021-01-26 06:59 UTC, min-w-park commented on app/src/main/java/com/codesoom/assignment/controllers/TaskController.java
> +                .created(task);
장단이 있어 보여요. 다른 것도 차라리 TaskResponseEntity를 사용해서 통일성을 줘도 괜찮을 것 같고요.
그렇지만 또 굳이 status와 body 만 더 쓰면 될 부분에 이렇게 해도 될까 싶기도 하고요? 
윤석님 생각은 어떠세요?

2021-01-26 06:59 UTC, min-w-park commented on app/src/main/java/com/codesoom/assignment/models/Task.java
> +    }
좋은 지적 고마워요.

2021-01-26 07:03 UTC, min-w-park commented on app/src/main/java/com/codesoom/assignment/controllers/TaskController.java
> +    }
네, 좋네요.

2021-01-26 14:15 UTC, hannut91 commented on app/src/main/java/com/codesoom/assignment/controllers/TaskController.java
> +                .created(task);
음.. 저는 아직 필요성을 잘 모르겠어요. 단순히 이렇게 해도 될 것 같아요

```java
@PostMapping
@ResponseStatus(HttpStatus.CREATED)
public Task createTask(@RequestBody Task task) {
    task.setId(generateId(taskId));
    tasks.add(task);
    return task;
}
```

2021-01-27 16:12 UTC, hannut91 commented
> modified variable name

커밋의 이름은 명령형으로 작성하는게 좋을 것 같아요.

2021-01-28 14:12 UTC, hannut91 commented on app/src/main/java/com/codesoom/assignment/controllers/TaskController.java
> +    private int taskId = 0;
`TaskController`가 할 일 목록을 어떻게 관리하는지 모두 가지고 있는 것 같아요. 관심사에 따라서 적절히 분리하는 것은 어떨까요?

2021-01-29 14:39 UTC, hannut91 commented
관심사의 분리는 꼭 해보시길 바랍니다!

2021-01-30 02:43 UTC, min-w-park commented on app/src/main/java/com/codesoom/assignment/controllers/TaskController.java
> +    private int taskId = 0;
`TaskService`로 따로 분리해 보았습니다.

2021-01-30 02:44 UTC, min-w-park commented
커밋의 이름이 명령형이면 `무엇을 했다`가 아니라, `무엇을 하다`. 라는 걸까요?

2021-01-30 13:39 UTC, hannut91 commented
> 요약하는 문장(예를 들어, 메시지의 첫출)은 간단명료한 설명이 되어야 합니다. 50글자를 넘지 않는 것이 바람직합니다. 대문자로 시작하는 명령형 현재시제를 사용해야 합니다. 커밋의 실질적인 제목이 되기 때문에 마침표(온점)로 끝나는 것은 바람직하지 않습니다.

커밋의 이름은 명령형 현재시제를 사용합니다 ㅎㅎ 

https://github.com/ikaruce/git-style-guide

2021-01-30 13:47 UTC, hannut91 commented on app/src/main/java/com/codesoom/assignment/controllers/TaskController.java
> +    }
HTTP 상태 코드를 `200 OK`로 전달하기 위해서 `ResponseEntity`로 하신 것 같습니다. 반환 타입이 `ResponseEntity`라서 무엇을 반환하는지 코드를 봐야지만 알 수 있네요.
HTTP 상태 코드는 `@ResponseStatus`로 이미 지정해주고 있으니 반환 타입은 `Task`로 쓰는 것은 어떨까요?
```suggestion
    @GetMapping("/{id}")
    @ResponseStatus(HttpStatus.OK)
    public Task getTask(@PathVariable long id) {
        return taskService.getTask(id);
    }
```

2021-01-30 13:47 UTC, hannut91 commented on app/src/main/java/com/codesoom/assignment/controllers/TaskController.java
> +    }
여기도 마찬가지로 반환 타입을 `ResponseEntity` 대신에 `Task`로 하면 좋을 것 같아요

2021-01-30 13:47 UTC, hannut91 commented on app/src/main/java/com/codesoom/assignment/controllers/TaskController.java
> +    }
해당하는 `task`가 없는 경우에는 `Not Found`를 돌려주고, 성공적으로 삭제했을 때는 `No Content`로 HTTP 상태 코드를 돌려주고 있는 것 같아요.
과제 풀이를 참고하여 Advice를 이용해서 에러 처리를 해주는 건 어떨가요? 

See also
  - https://spring.io/blog/2013/11/01/exception-handling-in-spring-mvc

2021-01-30 13:47 UTC, hannut91 commented on app/src/main/java/com/codesoom/assignment/services/TaskService.java
> +                .filter(i -> i.getId() == id)
`equals`를 이용해서 비교해야 할 것 같아요

2021-01-31 12:27 UTC, min-w-park commented
한 것
- Spring을 이용한 ToDo REST API 개발

느낀 것
- 프레임워크의 장점을 느낄 수 있어서 좋았다. 
- UI 개발에 시간이 좀 걸렸다. 복잡한 기능은 아니지만 익숙하지 않아서 그런건지.. 
- 평상시에 그냥 쓰던 기능에 대해 좀 더 생각해보고 찾아볼 수 있어 좋았다.

배운 것
- markojs.
- 커밋 작성법 
- ControllerAdvice 사용법

자기 선언
- JavaDoc을 작성해 보지 못했다. 좀 더 시간을 내자..
- 과제를 끝내는 것이 첫번째 목표가 아니라, 평상시 업무에서 시간에 쫓기어 제대로 공부하면서 개발 하지 못하는 태도를 버리고, 좀 더 배우려는 목적을 가지고 과제에 임하자

2021-01-31 14:15 UTC, hannut91 approved these changes
자기 선언이 굉장히 좋네요 ㅎㅎ 다음 과제에서는 더 많이 배워가셨으면 좋겠습니다! 고생하셨습니다

2021-01-31 14:15 UTC, merged