spring-week2-assignment-1
CodeSoom/spring-week2-assignment-1 pull request #86
Opened 2022-05-13 12:20 UTC by LeeJongbokz

안녕하세요 :) 2주차 과제 제출합니다.

감사합니다 :)

2022-05-13 13:21 UTC, ssisksl77 commented on app/src/main/java/com/codesoom/assignment/models/Task.java
> +    }
기본생성자를 제거해보는 시도를 해보면 좋은 경험이 될 거에요!

2022-05-13 13:22 UTC, ssisksl77 commented on app/src/main/java/com/codesoom/assignment/exception/TaskNotFoundException.java
> +    private Long newId = 0L;
Controller의 역할과는 맞지 않는 객체들이에요! 분리해보면 좋을 것 같아요!

2022-05-13 13:23 UTC, ssisksl77 commented on app/src/main/java/com/codesoom/assignment/controllers/TaskController.java
> +    private Long newId = 0L;
Controller의 역할과는 맞지 않는 객체들이에요! 분리해보면 좋을 것 같아요!

2022-05-13 13:23 UTC, ssisksl77 commented on app/src/main/java/com/codesoom/assignment/controllers/TaskController.java
> +    }
아이디를 생성하는 역할도 Controller 성격에는 맞지 않아요!

2022-05-13 13:24 UTC, ssisksl77 requested changes

2022-05-13 13:24 UTC, ssisksl77 commented on app/src/main/java/com/codesoom/assignment/exception/TaskNotFoundException.java
> +public class TaskController {
코드가 이상하네요! `TaskNotFoundException` 에 `TaskController` 가 있군요!

2022-05-15 04:46 UTC, LeeJongbokz commented on app/src/main/java/com/codesoom/assignment/models/Task.java
> +    }
기본 생성자를 왜 제거해야 할까요?

2022-05-15 04:47 UTC, LeeJongbokz commented on app/src/main/java/com/codesoom/assignment/controllers/TaskController.java
> +    }
Controller에 이런 메소드가 포함되어서는 안된다는 말씀일까요?

2022-05-15 04:47 UTC, LeeJongbokz commented on app/src/main/java/com/codesoom/assignment/exception/TaskNotFoundException.java
> +public class TaskController {
넵 이 부분 다시 확인하겠습니다

2022-05-15 05:04 UTC, LeeJongbokz commented on app/src/main/java/com/codesoom/assignment/controllers/TaskController.java
> +    }
저 이 리뷰랑은 상관 없는건데, 추가적으로 여쭙고 싶은게 있는데요~
제가 Exception 처리를 할 때, 다른 분 코드를 참고해서 
1) 사용자 정의 Exception
2) Optional  
을 사용하기도 했는데, 실무에서 1), 2) 중 어떤 것을 많이 사용하나요?
실제 사용자 정의 Exception을 많이 만들기도 하나요?

2022-05-15 06:51 UTC, ssisksl77 commented on app/src/main/java/com/codesoom/assignment/models/Task.java
> +    }
어쩌면 제가 너무 이유를 숨기고 요구를 한 것처럼 보이는 군요 ㅠㅜㅠㅜ

전혀 그렇지 않습니다.

기본생성자를 제거하는 이유는 여러가지 이유가 섞여있지만! 그중 가장 큰 이유는 `new Task()` 라는 코드가 만드신 코드베이스에 존재하지 않기 때문입니다!

2022-05-15 06:53 UTC, ssisksl77 commented on app/src/main/java/com/codesoom/assignment/models/Task.java
> +    }
그럼에도 분명 기본생성자를 만드신 이유는 아마 `Task` 를 Controller에서도 쓰기 위해서 일 것입니다! 좀 더 정확히 이야기 한다면, `@RequestBody` 에 `Task` 를 붙이기 위함일 수도 있겠어요

2022-05-15 06:54 UTC, ssisksl77 commented on app/src/main/java/com/codesoom/assignment/models/Task.java
> +    }
만약에 그렇다면, `@RequestBody` 에 넣기 위해 사용하지도 않는 기본생성자를 만들어서 구태여 `Task` 의 변수들이 `null` 에 취약하도록 만들 필요가 있을까요?

2022-05-15 12:12 UTC, ssisksl77 commented on app/src/main/java/com/codesoom/assignment/controllers/TaskController.java
> +    }
사실 Exception과 비교하는 기능은 Optional 은 아닙니다. 왜냐하면 Exception은 실패에 대한 여러가지 의미를 갖고 있지만 `Optional` 은 값의 유무만을 관여하거든요! 그리고 Exception으로 어디까지 핸들링 할까는 함께 일하는 팀원과 정합니다. 

지금처럼 간단한 CRUD Task 프로젝트에서 Service Repository 클래스를 만들어야 할까요? 라는 질문에 yes도 되고 no도 될 것 같아요!
yes : 요구사항이 간단하고 바뀔 일이 없다. 현 코드만으로 모든 요구사항은 일치한다.
no : 요구사항이 곧 복잡한 기획과 함께 올 것이므로, Service와 Repository를 나눠야 한다. 그리고 나누는데 큰 힘이 들지 않는다.

2022-05-15 12:14 UTC, ssisksl77 commented on app/src/main/java/com/codesoom/assignment/controllers/TaskController.java
> +    }
요구사항이 변할 일이 없음은 확실하죠!! 
하지만 무언가 새로운 것들을 경험하기 위해 이 자리에 오신 것이니 조심스레 제안을 드려본 것입니다 ㅎㅎ

2022-05-15 12:15 UTC, ssisksl77 commented on app/src/main/java/com/codesoom/assignment/controllers/TaskController.java
> +    }
> 넵 피드백 감사합니다ㅎㅎ Controller에 이런 메소드가 포함되어서는 안된다는 말씀일까요?

맞습니다! 컨트롤러는 유저의 요청에 따라 어느 객체에게 그 일을 위임할지만 생각하는 것이 좋아요!

2022-06-13 12:17 UTC, closed without merging